### ISSUE TITLE
Cannot use CoInvestor\LaraHook\Facades\Hook as Hook because the name is already in use

### ISSUE THREAD

**Issue by manyang-megantoro** [CoInvestor/larahook#6]
How to use multiple hook in one blade?

when I use multiple hook in one blade I get "Cannot use CoInvestor\LaraHook\Facades\Hook as Hook because the name is already in use"

when I look at the output of blade its make multiple "use CoInvestor\LaraHook\Facades\Hook;"

I think its bug in src/HookServiceProvider.php:40 and src/HookServiceProvider.php:65
it need to ask if "use CoInvestor\LaraHook\Facades\Hook;" has been added it not add it again.

**Comment by thybag** [comment]
Hi @manyang-megantoro - cheers for reporting this. I have replicated the bug in a test and added a fix in the branch `MultipleBladeHooks`. 

Please let me know if this resolves the issue for you.
